title: "My Awesome Blog"
email: ""
description: "A blog where I share my Python projects and experiences."
baseurl: "" # Leave empty for GitHub Pages
url: "https://shaminatf.github.io" # Your GitHub Pages URL

twitter_username: "your-twitter"
github_username: "shaminatf"

# Build settings
remote_theme: jekyll/minima # Use remote theme for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Helps with SEO

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
